# demo configuration
# see: https://docs.docker.com/compose/extends/#example-use-case
#
# -uses pre-build openchirp images
# -services store permament files on the host, under ./data/<service>
# -only map *essential* external ports
# -services are always restarted
# -logs have a maximum of 100m, and a maximum of 5 log files are kept
#
# *Logs*
#   # TODO: some container logs(mosquitto and rest) are mounted to data/ directory, but others arent. This needs some cleanup.
#    "json-file" logging will write logs to:
#    /var/lib/docker/containers/<container id>/<container id>-json.log
#    
#    You can use docker inspect to check this: 
#    docker inspect --format='{{.LogPath}}' $INSTANCE_ID
#    
# IMPORTANT: This is just a demonstration configuration. Use in production at your own peril.
# 
version: '2'

services:
  mongodb:
    volumes: 
      - ./data/mongodb:/data/db # permanent storage on the host
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always

  redis: 
    volumes:
      - ./data/redis/:/data # permanent storage on the host
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always
 
  influxdb: 
    volumes:
        - ./data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=false
      - INFLUXDB_GRAPHITE_ENABLED=false        
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always
   
  mosquitto: 
    image: openchirp/mosquitto
    volumes:
      - ./data/mosquitto/data:/var/lib/mosquitto # permanent storage on the host
      - ./data/mosquitto/log:/var/log/mosquitto # permanent storage on the host    
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    #restart: always

  grafana:
    image: openchirp/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    logging: 
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always

  web: 
    image: openchirp/web    
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always

  rest: 
    image: openchirp/rest   
    volumes:
      - ./data/node/log:/logs   
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always

  seed-data:
    image: openchirp/seed-data
    volumes:
      - ./data/tokens:/tokens # Mount tokens to host machine so that service containers can read them.   

  mqtt-influx-storage-service:
    image: openchirp/mqtt-influx-storage-service 
    volumes:
      - ./data/tokens:/tokens  # So that the service can read its token   
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always

  gpsmapper-service:
    image: openchirp/gpsmapper-service    
    volumes:
      - ./data/tokens:/tokens # So that the service can read its token
    logging:
      driver: "json-file" 
      options:
        max-size: "100m"
        max-file: "5"
    restart: always  
