# basic openchirp service configuration
# see: https://docs.docker.com/compose/extends/#example-use-case
#
version: '2'
services:
  mongodb:
    image: mongo:3.2.19 #  pulls from https://hub.docker.com/_/mongo/

  redis: 
    image: redis # pulls from https://hub.docker.com/_/redis/

  influxdb: 
    image: influxdb # pulls from https://hub.docker.com/_/influxdb/
    environment:
      - INFLUXDB_DB="openchirp"   
  
# Note that no build or image is specified for the services below
# because it is defined in docker-compose.override.yml and docker-compose.devel.yml 
# For demo setup in override, the pre-built images are pulled from docker hub.
# For dev setup in devel, images are built from source locally.

  mosquitto: 
    ports:
      - "1883:1883"
    hostname: mosquitto
    environment:
       - REST_MQTT_PASSWORD=${REST_MQTT_PASSWORD}
    depends_on:
      - mongodb  

  grafana:
    ports:
      - "3000:3000"    
    depends_on:
      - influxdb
    environment:
       - GF_AUTH_ANONYMOUS_ENABLED=true # For users to see custom grafana dashboard embedded in openchirp. That dashboard needs an id to show any real data.
       - GF_SECURITY_ADMIN_USER=admin
       - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    
  web: 
    ports:
      - "80:80"
    environment:
      - HOSTNAME=${HOSTNAME}

  rest: 
    ports:
      - "7000:10010"
    environment:
      - NODE_ENV=docker # will cause the node.js app to load the config/docker.json configuration file
      - REST_MQTT_PASSWORD=${REST_MQTT_PASSWORD}    
    depends_on:
      - mongodb
      - redis
      - influxdb
      - mosquitto

  # This container creates admin user, admin and developer group, root location and service tokens.   
  seed-data:
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD} 
    depends_on:
      - rest

  mqtt-influx-storage-service:
    depends_on:
      - seed-data
  
  gpsmapper-service:
    depends_on:
      - seed-data
    ports:
      - "9000:9000"  
