# basic openchirp service configuration
# see: https://docs.docker.com/compose/extends/#example-use-case
#
version: '2'
services:
  mongodb:
    image: mongo:3.2.19 # https://hub.docker.com/_/mongo/

  redis: 
    image: redis # https://hub.docker.com/_/redis/

  influxdb: 
    build: influxdb
    environment:
      - PRE_CREATE_DB="openchirp"   
      
  mosquitto: 
    ports:
      - "1883:1883"
    hostname: mosquitto
    environment:
       - REST_MQTT_PASSWORD=${REST_MQTT_PASSWORD}
    depends_on:
      - mongodb  

  grafana:
    ports:
      - "3000:3000"    
    depends_on:
      - influxdb
    
  web: 
    ports:
      - "80:80"

  rest: 
    ports:
      - "7000:10010"
    environment:
      - NODE_ENV=docker # will cause the node.js app to load the config/docker.json configuration file
      - REST_MQTT_PASSWORD=${REST_MQTT_PASSWORD}
      - ADMIN_PASSWORD =${ADMIN_PASSWORD}
    depends_on:
      - mongodb
      - redis
      - influxdb
      - mosquitto
    
  mqtt-influx-storage-service:
    depends_on:
      - rest
 #   command: bash -c "cat /etc/ssl/certs/mosquitto/ca.crt >> /etc/ssl/certs/ca-certificates.crt && 
 #                     cp -f /run/service.conf /code/ &&                                          
 #                     python influx_service.py -f service.conf"                                         
  
