#  development configuration (run using: docker-compose -f docker-compose.yml -f docker-compose.devel.yml up -d)
#  see: https://docs.docker.com/compose/extends/#example-use-case
#  
# -services *dot not* store permament files
# -map all service ports; rest API at port 10010
# -mounts source code from the host
#
# *Logs*
# 
#    By default logs are "json-file", and are written to: 
#    /var/lib/docker/containers/<container id>/<container id>-json.log
#    
#    You can use docker inspect to check this: 
#       docker inspect --format='{{.LogPath}}' $INSTANCE_ID
#       
#    *No maximum log sizes defined*
# 
version: '2'

services:
  mongodb:
    ports:
      - "27017:27017"
    command: "--smallfiles" # small files

  redis: 
    ports:
      - "6379:6379"

  influxdb: 
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true

  grafana:
    build: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  mosquitto: 
    build: mosquitto
    volumes:
      - ./mosquitto/certs:/etc/ssl/certs
    hostname:
      mosquitto-server
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"

  web: 
    build: httpd  
    volumes:
      - ./httpd/code:/openchirp
  
  rest: 
    build: node  
    volumes:
      - ./node/code:/usr/src/app
      - /usr/src/app/node_modules
   
  mqtt-influx-storage-service:
    build: mqtt-influx-storage-service    
    volumes:
      - ./mqtt-influx-storage-service/code:/code
      - ./mosquitto/certs:/etc/ssl/certs/mosquitto:ro
