# basic openchirp service configuration
# see: https://docs.docker.com/compose/extends/#example-use-case
#
version: '2'
#TODO: change links to depends_on and change version to 3
services:
  mongodb:
    image: mongo # https://hub.docker.com/_/mongo/

  redis: 
    image: redis # https://hub.docker.com/_/redis/

  influxdb: 
    build: influxdb
    environment:
      - PRE_CREATE_DB="openchirp"   
      
  mosquitto: 
    build: mosquitto # https://hub.docker.com/_/eclipse-mosquitto/
    ports:
      - "1883:1883"
    hostname: mosquitto
    links:
      - mongodb
      - influxdb

  grafana:
    ports:
      - "3000:3000"    
    links:
      - influxdb
    depends_on:
      - influxdb
    
  web: 
    ports:
      - "80:80"

  rest: 
    ports:
      - "7000:10010"
    links:
      - mongodb
      - redis
      - influxdb
    command: npm start
#TODO: Run multiple commands ? A script that creates root location and other stuff post start or a separate service ?

  mqtt-influx-storage-service:
    links:
      - rest
      - mosquitto:mosquitto-server
      - influxdb  
    command: bash -c "cat /etc/ssl/certs/mosquitto/ca.crt >> /etc/ssl/certs/ca-certificates.crt && 
                      cp -f /run/service.conf /code/ &&                                          
                      python influx_service.py -f service.conf"                                         
  
